### ISSUE TITLE
Admin password generation vs. docs

### ISSUE THREAD

**Issue by pablorq** [mik-p/docker-wintercms#1]
- Winter CMS Build: hiltonbanes/wintercms:build.v1.1.2 
- PHP Version:
- Database Engine: mariadb:10.4 
- Plugins Installed: none 

### Description:

The [Quick Start](https://github.com/mik-p/docker-wintercms#quick-start) says:

> Login to the backend with the username `admin` and password `admin`.

After install it a random password is generated, which is a problem not only because it is not matching the docs but also when using tools like Portainer, where the generated password is not easy to retrieve.

### Steps To Reproduce:

Install WinterCMS with the [docker-compose](https://github.com/mik-p/docker-wintercms#mysql--postgres) file with database support.

Run:
```
$ docker-compose up -d
$ docker-compose exec web php artisan winter:up

...

Winter.Demo
 - v1.0.1:  First version of Demo
Seeded System 
Seeded Backend 

\Backend\Database\Seeds\DatabaseSeeder reported:
 - The following password has been automatically generated for the "admin" account: Tnq1g8Uj45itsKnYIkVC7p
```

Go to the backend page.

Try `admin:admin` as specified on the docs.

It doesn't work.

### Spected Behaviour
Use `admin:admin` as specified on the docs to access the backend.

**Comment by pablorq** [comment]
Using this:

```
docker exec -it container_name winter passwd admin admin
```

... as suggested in [wintercms issue](https://github.com/wintercms/winter/issues/95#issuecomment-823292569) could be a solution if you work with docker from command line.

But in my case, I use Portainer and create stacks for each app, and this solution is not easy to use.

I think that the best way is to have `admin:admin` by default, specially when used with the `INIT_WINTER=true` variable.

**Comment by bennothommo** [comment]
@pablorq just to note, the docs are out of date. Setting a default of `admin` / `admin` is not a good security practice, hence why we put the generated password on install.

**Comment by pablorq** [comment]
@bennothommo I know that is not a good practice.

The point I'm trying to focus on is to deploy docker-wintercms with tools like Portainer or Kubernetes. And for this is necessary to setup the admin password outside the container, without having to get into it to extract the admin password.

I was trying to do that by adding this to the docker-compose file (as detailed [here](https://github.com/mik-p/docker-wintercms#docker-entrypoint)):
```
    environment:
    ...
      - INIT_WINTER=true
      - CMS_ADMIN_PASSWORD=admin
```

But it doesn't work. The password is randomly generated inside the container.

Any other ideas?

**Comment by mik-p** [comment]
I just added this and need to properly test it. I think there may be some timing issues with the DB coming up and the winter:up occurring (and crashing) too early. I'm adding more detail on the subject at the moment

**Comment by mik-p** [comment]
I have tested the combination of environment options and I have added an example docker compose file for fixing timing.

See [examples/init-winter/docker-compose.yml](https://github.com/mik-p/docker-wintercms/blob/master/examples/init-winter/docker-compose.yml)

this [commit](https://github.com/mik-p/docker-wintercms/commit/3022d2beaeb722469f411ae1508c450748a05cca)

I think this is as far as I would like to automate. I think any further automation might be better implemented by extending the base image in a cutom Dockerfile

**Comment by bennothommo** [comment]
I'd say that's all you need @mik-p - nice one!
