### ISSUE TITLE
Update to Winter CMS v1.2.1?

### ISSUE THREAD

**Issue by tamer-hassan** [mik-p/docker-wintercms#5]
Per: https://wintercms.com/releases/v1.2.1
Released: October 20, 2022

**Comment by tamer-hassan** [comment]
https://github.com/mik-p/docker-wintercms/pull/6

**Comment by yasdevops** [comment]
Solved by https://github.com/mik-p/docker-wintercms/pull/6 which is merged now

**Comment by tamer-hassan** [comment]
Solved after merge of https://github.com/mik-p/docker-wintercms/pull/6
