### ISSUE TITLE
sitemap.xml - 404

### ISSUE THREAD

**Issue by comerc** [mik-p/docker-wintercms#7]
How to setup sitemap.xml?

https://github.com/wintercms/wn-sitemap-plugin

> The Sitemap plugin works out of the box and does not require any direct development to operate.

**Comment by mik-p** [comment]
From experience with the sitemap plugin, I think that there is an initial set up in the backend plugin GUI. If there was a CLI tool from the sitemap plugin you could add a custom entrypoint to run this command on start to set up automatically

**Comment by mik-p** [comment]
#8
